export const vaccins = [
  {
    // Vaccin 1,
    nom: 'BBIBP-CorV',
    inventeurs: 'Sinopharm',
    lieuxDeProduction: 'Chine',
    technologie: 'virus inactivé',
    quantite: 420,
    prixUnitaire: 17,
    approuve: true,
    image: 'bbibp-Corv.jpg',
    reserve: false,

  },
  {
    // Vaccin 2,
    nom: 'Sputnik V',
    inventeurs: 'Gamaleya',
    lieuxDeProduction: ['Russie', 'Inde'],
    technologie: 'adenovirus',
    quantite: 130,
    prixUnitaire: 12,
    approuve: false,
    image: 'sputnik-v.jpg',
    reserve: false,
  },
  {
    // Vaccin 3
    nom: 'AZD1222',
    inventeurs: ['AstraZeneca', 'University of Oxford'],
    lieuxDeProduction: ['Royaume Unis', 'Brésil', 'Inde'],
    technologie: 'adenovirus',
    Quantité: 5028,
    prixUnitaire: 1.78,
    approuve: false,
    image: 'azd1222.jpg',
    reserve: false,

  },
  {
    // Vaccin 4
    nom: 'Tozinameran',
    inventeurs: ['BioNTech', 'Pfizer', 'Fosun Pharma'],
    lieuxDeProduction: ['Allemagne', 'USA'],
    technologie: 'ARN messager',
    Quantité: 980,
    prixUnitaire: 14,
    approuve: true,
    image: 'tozinameran.jpg',
    reserve: false,
  },
  {
    // Vaccin 5
    nom: 'mRNA-1273',
    inventeurs: ['Moderna', 'NIAID', 'BARDA'],
    lieuxDeProduction: 'USA',
    technologie: 'ARN messager',
    quantite: 240,
    prixUnitaire: 28,
    approuve: false,
    image: 'mrna-1273.jpg',
    reserve: false,
  },
  {
    // Vaccin 6
    nom: 'Ad26.COV2.S',
    inventeurs: ['Johnson & Johnson', 'BIDMC'],
    lieuxDeProduction: ['USA', 'Amérique du Sud', 'Ukraine', 'Afrique du Sud'],
    technologie: 'adenovirus',
    Quantité: 110,
    prixUnitaire: 31,
    approuve: false,
    image: 'ad26-cov2-s.jpg',
    reserve: false,
  },
];
